[book]
authors = ["Elham Aryanpur"]
language = "en"
multilingual = false
src = "src"
title = "Blue Engine"
description = "The official documentation of the Blue Engine"

[build]
build-dir = "docs"
create-missing = false