[book]
authors = ["Elham Aryanpur"]
language = "en"
multilingual = false
src = "src"
title = "Blue Engine"
description = "The official documentation of the Blue Engine"

[build]
build-dir = "docs"
create-missing = false

[output.html]
git-repository-url = "https://github.com/AryanpurTech/BlueEngineDocs"
edit-url-template = "https://github.com/AryanpurTech/BlueEngineDocs/edit/master/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
